baseURL: 'https://frolicking-panda-209d24.netlify.app'
languageCode: en-us
title: Abdur Rahman
theme: PaperMod

menu:
  main:
  - identifier: home
    name: Home
    url: /
    weight: 10
  - identifier: blog
    name: Blog
    url: /blog
    weight: 20
  - identifier: projects
    name: Projects
    url: /projects
    weight: 30
  - identifier: experience
    name: Experience
    url: /experience
    weight: 40
  - identifier: search
    name: Search
    url: /search
    weight: 50
  - identifier: tags
    name: Tags
    url: /tags
    weight: 60
  # - identifier: archives
  #   name: Archives
  #   url: /archives
  #   weight: 50

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # Home Page
  profileMode:
    enabled: true
    title: "Abdur Rahman" # optional default will be site title
    subtitle: I'm an incoming student at the **University of Toronto**, Canada 🇨🇦 for their MSc in Applied Computing program. Currently, I am working as a Backend Engineer 🧑🏻‍💻 at BuyerAssist.io, a B2B startup based in Pune, India 🇮🇳. <br> I have an extensive background in Deep Learning and Computer Vision through my projects and internship that I did back in college. I have completed my Bachelor of Technology (B.Tech) in Electronics & Communication Engineering from NIT Trichy, one of India's top 10 schools for engineering.
    imageUrl: "home/me.jpg" # optional
    imageWidth: 220
    imageHeight: 220
    # buttons:
    #   - name: Blog
    #     url: "/blog"
    #   - name: Projects
    #     url: "/projects"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:abdur.rahman.kalim@gmail.com"
    - name: "youtube"
      url: "https://www.youtube.com/c/AbdurRahmanKalim"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/abdurrahmankalim"
    - name: "github"
      url: "https://github.com/arkalim"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true