baseURL: 'https://arkalim.org'
languageCode: en-us
title: Abdur Rahman
theme: PaperMod

menu:
  main:
  - identifier: home
    name: Home
    url: /
    weight: 10
  - identifier: blog
    name: Blog
    url: /blog
    weight: 20
  - identifier: projects
    name: Projects
    url: /projects
    weight: 30
  - identifier: experience
    name: Experience
    url: /experience
    weight: 40
  - identifier: search
    name: Search
    url: /search
    weight: 50
  - identifier: tags
    name: Tags
    url: /tags
    weight: 60

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Abdur Rahman"
    subtitle: I'm an incoming student at the **University of Toronto**, Canada 🇨🇦 for their [**MSc in Applied Computing**](https://mscac.utoronto.ca/) program. I'm currently working as a Backend Engineer 🧑🏻‍💻 at [**BuyerAssist.io**](https://buyerassist.io/), a B2B startup based in India 🇮🇳. I have completed my Bachelor of Technology (B.Tech) in Electronics & Communication Engineering from **NIT Trichy**, one of India's top 10 schools for engineering. I consume a lot of self-improvement content predominantly in the form of books & videos. As a content creator on **YouTube** 🎬, I make videos about career, higher education, technology and productivity.
    imageUrl: "home/me.jpg" # optional
    imageWidth: 220
    imageHeight: 220
    # buttons:
    #   - name: Resume
    #     url: "https://drive.google.com/file/d/15bupi_Ez5GhhNa2LIT7an1Qxg-0XKYH2/view"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:abdur.rahman.kalim@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/abdurrahmankalim"
    - name: "github"
      url: "https://github.com/arkalim"
    - name: "youtube"
      url: "https://www.youtube.com/c/AbdurRahmanKalim"
    - name: "cv"
      url: "https://drive.google.com/file/d/15bupi_Ez5GhhNa2LIT7an1Qxg-0XKYH2/view"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true